default:  fxctmp9_tmp\flowmappedwater_vs20.inc shaders\fxc\flowmappedwater_vs20.vcs fxctmp9_tmp\flowmappedwater_ps20.inc shaders\fxc\flowmappedwater_ps20.vcs fxctmp9_tmp\flowmappedwater_ps20b.inc shaders\fxc\flowmappedwater_ps20b.vcs

fxctmp9_tmp\flowmappedwater_vs20.inc shaders\fxc\flowmappedwater_vs20.vcs: flowmappedwater_vs20.fxc common_hlsl_cpp_consts.h common_vs_fxc.h common_pragmas.h common_fxc.h
	perl ..\..\devtools\bin\fxc_prep.pl   -source "..\.." flowmappedwater_vs20.fxc-----flowmappedwater_vs20
	echo flowmappedwater_vs20.fxc>> filestocopy.txt
	echo common_hlsl_cpp_consts.h>> filestocopy.txt
	echo common_vs_fxc.h>> filestocopy.txt
	echo common_pragmas.h>> filestocopy.txt
	echo common_fxc.h>> filestocopy.txt

fxctmp9_tmp\flowmappedwater_ps20.inc shaders\fxc\flowmappedwater_ps20.vcs: flowmappedwater_ps2x.fxc common_vertexlitgeneric_dx9.h common_fxc.h common_pragmas.h common_ps_fxc.h common_fog_ps_fxc.h shader_constant_register_map.h common_flashlight_fxc.h common_hlsl_cpp_consts.h
	perl ..\..\devtools\bin\fxc_prep.pl   -source "..\.." flowmappedwater_ps2x.fxc-----flowmappedwater_ps20
	echo flowmappedwater_ps2x.fxc>> filestocopy.txt
	echo common_vertexlitgeneric_dx9.h>> filestocopy.txt
	echo common_fxc.h>> filestocopy.txt
	echo common_pragmas.h>> filestocopy.txt
	echo common_ps_fxc.h>> filestocopy.txt
	echo common_fog_ps_fxc.h>> filestocopy.txt
	echo shader_constant_register_map.h>> filestocopy.txt
	echo common_flashlight_fxc.h>> filestocopy.txt
	echo common_hlsl_cpp_consts.h>> filestocopy.txt

fxctmp9_tmp\flowmappedwater_ps20b.inc shaders\fxc\flowmappedwater_ps20b.vcs: flowmappedwater_ps2x.fxc common_vertexlitgeneric_dx9.h common_fxc.h common_pragmas.h common_ps_fxc.h common_fog_ps_fxc.h shader_constant_register_map.h common_flashlight_fxc.h common_hlsl_cpp_consts.h
	perl ..\..\devtools\bin\fxc_prep.pl   -source "..\.." flowmappedwater_ps2x.fxc-----flowmappedwater_ps20b
	echo flowmappedwater_ps2x.fxc>> filestocopy.txt
	echo common_vertexlitgeneric_dx9.h>> filestocopy.txt
	echo common_fxc.h>> filestocopy.txt
	echo common_pragmas.h>> filestocopy.txt
	echo common_ps_fxc.h>> filestocopy.txt
	echo common_fog_ps_fxc.h>> filestocopy.txt
	echo shader_constant_register_map.h>> filestocopy.txt
	echo common_flashlight_fxc.h>> filestocopy.txt
	echo common_hlsl_cpp_consts.h>> filestocopy.txt

